version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somegraphql
      MYSQL_DATABASE: graphql
      MYSQL_USER: graphql
      MYSQL_PASSWORD: graphql
volumes:
  db_data: {}